/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.inf.iSCL.ISCLPackage;
import uk.ac.kcl.inf.iSCL.PaymentTerm;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Payment Term</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.iSCL.impl.PaymentTermImpl#getPremium <em>Premium</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.impl.PaymentTermImpl#getPeriod <em>Period</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.impl.PaymentTermImpl#getIncrease <em>Increase</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PaymentTermImpl extends MinimalEObjectImpl.Container implements PaymentTerm
{
  /**
   * The default value of the '{@link #getPremium() <em>Premium</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPremium()
   * @generated
   * @ordered
   */
  protected static final float PREMIUM_EDEFAULT = 0.0F;

  /**
   * The cached value of the '{@link #getPremium() <em>Premium</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPremium()
   * @generated
   * @ordered
   */
  protected float premium = PREMIUM_EDEFAULT;

  /**
   * The default value of the '{@link #getPeriod() <em>Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPeriod()
   * @generated
   * @ordered
   */
  protected static final int PERIOD_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPeriod() <em>Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPeriod()
   * @generated
   * @ordered
   */
  protected int period = PERIOD_EDEFAULT;

  /**
   * The default value of the '{@link #getIncrease() <em>Increase</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncrease()
   * @generated
   * @ordered
   */
  protected static final int INCREASE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getIncrease() <em>Increase</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncrease()
   * @generated
   * @ordered
   */
  protected int increase = INCREASE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PaymentTermImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ISCLPackage.Literals.PAYMENT_TERM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public float getPremium()
  {
    return premium;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPremium(float newPremium)
  {
    float oldPremium = premium;
    premium = newPremium;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ISCLPackage.PAYMENT_TERM__PREMIUM, oldPremium, premium));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPeriod()
  {
    return period;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPeriod(int newPeriod)
  {
    int oldPeriod = period;
    period = newPeriod;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ISCLPackage.PAYMENT_TERM__PERIOD, oldPeriod, period));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getIncrease()
  {
    return increase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIncrease(int newIncrease)
  {
    int oldIncrease = increase;
    increase = newIncrease;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ISCLPackage.PAYMENT_TERM__INCREASE, oldIncrease, increase));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ISCLPackage.PAYMENT_TERM__PREMIUM:
        return getPremium();
      case ISCLPackage.PAYMENT_TERM__PERIOD:
        return getPeriod();
      case ISCLPackage.PAYMENT_TERM__INCREASE:
        return getIncrease();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ISCLPackage.PAYMENT_TERM__PREMIUM:
        setPremium((Float)newValue);
        return;
      case ISCLPackage.PAYMENT_TERM__PERIOD:
        setPeriod((Integer)newValue);
        return;
      case ISCLPackage.PAYMENT_TERM__INCREASE:
        setIncrease((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ISCLPackage.PAYMENT_TERM__PREMIUM:
        setPremium(PREMIUM_EDEFAULT);
        return;
      case ISCLPackage.PAYMENT_TERM__PERIOD:
        setPeriod(PERIOD_EDEFAULT);
        return;
      case ISCLPackage.PAYMENT_TERM__INCREASE:
        setIncrease(INCREASE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ISCLPackage.PAYMENT_TERM__PREMIUM:
        return premium != PREMIUM_EDEFAULT;
      case ISCLPackage.PAYMENT_TERM__PERIOD:
        return period != PERIOD_EDEFAULT;
      case ISCLPackage.PAYMENT_TERM__INCREASE:
        return increase != INCREASE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (premium: ");
    result.append(premium);
    result.append(", period: ");
    result.append(period);
    result.append(", increase: ");
    result.append(increase);
    result.append(')');
    return result.toString();
  }

} //PaymentTermImpl
