/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.inf.iSCL.ISCLPackage;
import uk.ac.kcl.inf.iSCL.PremiumIncreaseTerm;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Premium Increase Term</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.iSCL.impl.PremiumIncreaseTermImpl#getPremiumIncrease <em>Premium Increase</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PremiumIncreaseTermImpl extends ViolationTermImpl implements PremiumIncreaseTerm
{
  /**
   * The default value of the '{@link #getPremiumIncrease() <em>Premium Increase</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPremiumIncrease()
   * @generated
   * @ordered
   */
  protected static final int PREMIUM_INCREASE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPremiumIncrease() <em>Premium Increase</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPremiumIncrease()
   * @generated
   * @ordered
   */
  protected int premiumIncrease = PREMIUM_INCREASE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PremiumIncreaseTermImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ISCLPackage.Literals.PREMIUM_INCREASE_TERM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPremiumIncrease()
  {
    return premiumIncrease;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPremiumIncrease(int newPremiumIncrease)
  {
    int oldPremiumIncrease = premiumIncrease;
    premiumIncrease = newPremiumIncrease;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ISCLPackage.PREMIUM_INCREASE_TERM__PREMIUM_INCREASE, oldPremiumIncrease, premiumIncrease));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ISCLPackage.PREMIUM_INCREASE_TERM__PREMIUM_INCREASE:
        return getPremiumIncrease();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ISCLPackage.PREMIUM_INCREASE_TERM__PREMIUM_INCREASE:
        setPremiumIncrease((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ISCLPackage.PREMIUM_INCREASE_TERM__PREMIUM_INCREASE:
        setPremiumIncrease(PREMIUM_INCREASE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ISCLPackage.PREMIUM_INCREASE_TERM__PREMIUM_INCREASE:
        return premiumIncrease != PREMIUM_INCREASE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (premiumIncrease: ");
    result.append(premiumIncrease);
    result.append(')');
    return result.toString();
  }

} //PremiumIncreaseTermImpl
