/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.inf.iSCL.ISCLPackage;
import uk.ac.kcl.inf.iSCL.ViolationTerm;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Violation Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ViolationTermImpl extends MinimalEObjectImpl.Container implements ViolationTerm
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ViolationTermImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ISCLPackage.Literals.VIOLATION_TERM;
  }

} //ViolationTermImpl
