/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.parser.antlr.internal.InternalISCLParser;
import uk.ac.kcl.inf.services.ISCLGrammarAccess;

public class ISCLParser extends AbstractAntlrParser {

	@Inject
	private ISCLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalISCLParser createParser(XtextTokenStream stream) {
		return new InternalISCLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Contract";
	}

	public ISCLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ISCLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
