/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ISCLStandaloneSetup extends ISCLStandaloneSetupGenerated {

	public static void doSetup() {
		new ISCLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
