/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ISCLUiModule extends AbstractISCLUiModule {

	public ISCLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
