/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Claim Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.iSCL.ClaimTerm#getClaim <em>Claim</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.ClaimTerm#getClaimer <em>Claimer</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getClaimTerm()
 * @model
 * @generated
 */
public interface ClaimTerm extends EObject
{
  /**
   * Returns the value of the '<em><b>Claim</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Claim</em>' attribute.
   * @see #setClaim(float)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getClaimTerm_Claim()
   * @model
   * @generated
   */
  float getClaim();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.ClaimTerm#getClaim <em>Claim</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Claim</em>' attribute.
   * @see #getClaim()
   * @generated
   */
  void setClaim(float value);

  /**
   * Returns the value of the '<em><b>Claimer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Claimer</em>' reference.
   * @see #setClaimer(Customer)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getClaimTerm_Claimer()
   * @model
   * @generated
   */
  Customer getClaimer();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.ClaimTerm#getClaimer <em>Claimer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Claimer</em>' reference.
   * @see #getClaimer()
   * @generated
   */
  void setClaimer(Customer value);

} // ClaimTerm
