/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Claim Reduction Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.iSCL.ClaimReductionTerm#getClaimReduction <em>Claim Reduction</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getClaimReductionTerm()
 * @model
 * @generated
 */
public interface ClaimReductionTerm extends ViolationTerm
{
  /**
   * Returns the value of the '<em><b>Claim Reduction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Claim Reduction</em>' attribute.
   * @see #setClaimReduction(int)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getClaimReductionTerm_ClaimReduction()
   * @model
   * @generated
   */
  int getClaimReduction();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.ClaimReductionTerm#getClaimReduction <em>Claim Reduction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Claim Reduction</em>' attribute.
   * @see #getClaimReduction()
   * @generated
   */
  void setClaimReduction(int value);

} // ClaimReductionTerm
