/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contract</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.iSCL.Contract#getType <em>Type</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.Contract#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.Contract#getCompany <em>Company</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.Contract#getCustomers <em>Customers</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.Contract#getInsurableObjects <em>Insurable Objects</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.Contract#getPaymentTerm <em>Payment Term</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.Contract#getClaimTerm <em>Claim Term</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.Contract#getViolationTerms <em>Violation Terms</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getContract()
 * @model
 * @generated
 */
public interface Contract extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.iSCL.ContractType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see uk.ac.kcl.inf.iSCL.ContractType
   * @see #setType(ContractType)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getContract_Type()
   * @model
   * @generated
   */
  ContractType getType();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.Contract#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see uk.ac.kcl.inf.iSCL.ContractType
   * @see #getType()
   * @generated
   */
  void setType(ContractType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getContract_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.Contract#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Company</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Company</em>' containment reference.
   * @see #setCompany(Company)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getContract_Company()
   * @model containment="true"
   * @generated
   */
  Company getCompany();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.Contract#getCompany <em>Company</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Company</em>' containment reference.
   * @see #getCompany()
   * @generated
   */
  void setCompany(Company value);

  /**
   * Returns the value of the '<em><b>Customers</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.iSCL.Customer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Customers</em>' containment reference list.
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getContract_Customers()
   * @model containment="true"
   * @generated
   */
  EList<Customer> getCustomers();

  /**
   * Returns the value of the '<em><b>Insurable Objects</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.iSCL.InsurableObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Insurable Objects</em>' containment reference list.
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getContract_InsurableObjects()
   * @model containment="true"
   * @generated
   */
  EList<InsurableObject> getInsurableObjects();

  /**
   * Returns the value of the '<em><b>Payment Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Payment Term</em>' containment reference.
   * @see #setPaymentTerm(PaymentTerm)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getContract_PaymentTerm()
   * @model containment="true"
   * @generated
   */
  PaymentTerm getPaymentTerm();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.Contract#getPaymentTerm <em>Payment Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Payment Term</em>' containment reference.
   * @see #getPaymentTerm()
   * @generated
   */
  void setPaymentTerm(PaymentTerm value);

  /**
   * Returns the value of the '<em><b>Claim Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Claim Term</em>' containment reference.
   * @see #setClaimTerm(ClaimTerm)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getContract_ClaimTerm()
   * @model containment="true"
   * @generated
   */
  ClaimTerm getClaimTerm();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.Contract#getClaimTerm <em>Claim Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Claim Term</em>' containment reference.
   * @see #getClaimTerm()
   * @generated
   */
  void setClaimTerm(ClaimTerm value);

  /**
   * Returns the value of the '<em><b>Violation Terms</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.iSCL.ViolationTerm}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Violation Terms</em>' containment reference list.
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getContract_ViolationTerms()
   * @model containment="true"
   * @generated
   */
  EList<ViolationTerm> getViolationTerms();

} // Contract
