/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contract Cancellation Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.iSCL.ContractCancellationTerm#isCancelled <em>Cancelled</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getContractCancellationTerm()
 * @model
 * @generated
 */
public interface ContractCancellationTerm extends ViolationTerm
{
  /**
   * Returns the value of the '<em><b>Cancelled</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cancelled</em>' attribute.
   * @see #setCancelled(boolean)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getContractCancellationTerm_Cancelled()
   * @model
   * @generated
   */
  boolean isCancelled();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.ContractCancellationTerm#isCancelled <em>Cancelled</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cancelled</em>' attribute.
   * @see #isCancelled()
   * @generated
   */
  void setCancelled(boolean value);

} // ContractCancellationTerm
