/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Customer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.iSCL.Customer#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.Customer#getCoverage <em>Coverage</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.Customer#getParticipation <em>Participation</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getCustomer()
 * @model
 * @generated
 */
public interface Customer extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getCustomer_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.Customer#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Coverage</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.iSCL.Coverage}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coverage</em>' attribute.
   * @see uk.ac.kcl.inf.iSCL.Coverage
   * @see #setCoverage(Coverage)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getCustomer_Coverage()
   * @model
   * @generated
   */
  Coverage getCoverage();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.Customer#getCoverage <em>Coverage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coverage</em>' attribute.
   * @see uk.ac.kcl.inf.iSCL.Coverage
   * @see #getCoverage()
   * @generated
   */
  void setCoverage(Coverage value);

  /**
   * Returns the value of the '<em><b>Participation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Participation</em>' attribute.
   * @see #setParticipation(int)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getCustomer_Participation()
   * @model
   * @generated
   */
  int getParticipation();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.Customer#getParticipation <em>Participation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Participation</em>' attribute.
   * @see #getParticipation()
   * @generated
   */
  void setParticipation(int value);

} // Customer
