/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insurable Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.iSCL.InsurableObject#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.iSCL.InsurableObject#getOwner <em>Owner</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getInsurableObject()
 * @model
 * @generated
 */
public interface InsurableObject extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getInsurableObject_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.InsurableObject#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Owner</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owner</em>' reference.
   * @see #setOwner(Customer)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getInsurableObject_Owner()
   * @model
   * @generated
   */
  Customer getOwner();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.InsurableObject#getOwner <em>Owner</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owner</em>' reference.
   * @see #getOwner()
   * @generated
   */
  void setOwner(Customer value);

} // InsurableObject
