/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.iSCL.ISCLPackage
 * @generated
 */
public interface ISCLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ISCLFactory eINSTANCE = uk.ac.kcl.inf.iSCL.impl.ISCLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Contract</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract</em>'.
   * @generated
   */
  Contract createContract();

  /**
   * Returns a new object of class '<em>Payment Term</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Payment Term</em>'.
   * @generated
   */
  PaymentTerm createPaymentTerm();

  /**
   * Returns a new object of class '<em>Claim Term</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Claim Term</em>'.
   * @generated
   */
  ClaimTerm createClaimTerm();

  /**
   * Returns a new object of class '<em>Violation Term</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Violation Term</em>'.
   * @generated
   */
  ViolationTerm createViolationTerm();

  /**
   * Returns a new object of class '<em>Contract Cancellation Term</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract Cancellation Term</em>'.
   * @generated
   */
  ContractCancellationTerm createContractCancellationTerm();

  /**
   * Returns a new object of class '<em>Claim Reduction Term</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Claim Reduction Term</em>'.
   * @generated
   */
  ClaimReductionTerm createClaimReductionTerm();

  /**
   * Returns a new object of class '<em>Premium Increase Term</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Premium Increase Term</em>'.
   * @generated
   */
  PremiumIncreaseTerm createPremiumIncreaseTerm();

  /**
   * Returns a new object of class '<em>Customer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Customer</em>'.
   * @generated
   */
  Customer createCustomer();

  /**
   * Returns a new object of class '<em>Company</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Company</em>'.
   * @generated
   */
  Company createCompany();

  /**
   * Returns a new object of class '<em>Insurable Object</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Insurable Object</em>'.
   * @generated
   */
  InsurableObject createInsurableObject();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ISCLPackage getISCLPackage();

} //ISCLFactory
