/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.iSCL.ISCLFactory
 * @model kind="package"
 * @generated
 */
public interface ISCLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "iSCL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/ISCL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "iSCL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ISCLPackage eINSTANCE = uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.iSCL.impl.ContractImpl <em>Contract</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.iSCL.impl.ContractImpl
   * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getContract()
   * @generated
   */
  int CONTRACT = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__NAME = 1;

  /**
   * The feature id for the '<em><b>Company</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__COMPANY = 2;

  /**
   * The feature id for the '<em><b>Customers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__CUSTOMERS = 3;

  /**
   * The feature id for the '<em><b>Insurable Objects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__INSURABLE_OBJECTS = 4;

  /**
   * The feature id for the '<em><b>Payment Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__PAYMENT_TERM = 5;

  /**
   * The feature id for the '<em><b>Claim Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__CLAIM_TERM = 6;

  /**
   * The feature id for the '<em><b>Violation Terms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__VIOLATION_TERMS = 7;

  /**
   * The number of structural features of the '<em>Contract</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.iSCL.impl.PaymentTermImpl <em>Payment Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.iSCL.impl.PaymentTermImpl
   * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getPaymentTerm()
   * @generated
   */
  int PAYMENT_TERM = 1;

  /**
   * The feature id for the '<em><b>Premium</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_TERM__PREMIUM = 0;

  /**
   * The feature id for the '<em><b>Period</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_TERM__PERIOD = 1;

  /**
   * The feature id for the '<em><b>Increase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_TERM__INCREASE = 2;

  /**
   * The number of structural features of the '<em>Payment Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_TERM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.iSCL.impl.ClaimTermImpl <em>Claim Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.iSCL.impl.ClaimTermImpl
   * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getClaimTerm()
   * @generated
   */
  int CLAIM_TERM = 2;

  /**
   * The feature id for the '<em><b>Claim</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAIM_TERM__CLAIM = 0;

  /**
   * The feature id for the '<em><b>Claimer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAIM_TERM__CLAIMER = 1;

  /**
   * The number of structural features of the '<em>Claim Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAIM_TERM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.iSCL.impl.ViolationTermImpl <em>Violation Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.iSCL.impl.ViolationTermImpl
   * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getViolationTerm()
   * @generated
   */
  int VIOLATION_TERM = 3;

  /**
   * The number of structural features of the '<em>Violation Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIOLATION_TERM_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.iSCL.impl.ContractCancellationTermImpl <em>Contract Cancellation Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.iSCL.impl.ContractCancellationTermImpl
   * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getContractCancellationTerm()
   * @generated
   */
  int CONTRACT_CANCELLATION_TERM = 4;

  /**
   * The feature id for the '<em><b>Cancelled</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT_CANCELLATION_TERM__CANCELLED = VIOLATION_TERM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Contract Cancellation Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT_CANCELLATION_TERM_FEATURE_COUNT = VIOLATION_TERM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.iSCL.impl.ClaimReductionTermImpl <em>Claim Reduction Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.iSCL.impl.ClaimReductionTermImpl
   * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getClaimReductionTerm()
   * @generated
   */
  int CLAIM_REDUCTION_TERM = 5;

  /**
   * The feature id for the '<em><b>Claim Reduction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAIM_REDUCTION_TERM__CLAIM_REDUCTION = VIOLATION_TERM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Claim Reduction Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAIM_REDUCTION_TERM_FEATURE_COUNT = VIOLATION_TERM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.iSCL.impl.PremiumIncreaseTermImpl <em>Premium Increase Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.iSCL.impl.PremiumIncreaseTermImpl
   * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getPremiumIncreaseTerm()
   * @generated
   */
  int PREMIUM_INCREASE_TERM = 6;

  /**
   * The feature id for the '<em><b>Premium Increase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREMIUM_INCREASE_TERM__PREMIUM_INCREASE = VIOLATION_TERM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Premium Increase Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREMIUM_INCREASE_TERM_FEATURE_COUNT = VIOLATION_TERM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.iSCL.impl.CustomerImpl <em>Customer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.iSCL.impl.CustomerImpl
   * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getCustomer()
   * @generated
   */
  int CUSTOMER = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMER__NAME = 0;

  /**
   * The feature id for the '<em><b>Coverage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMER__COVERAGE = 1;

  /**
   * The feature id for the '<em><b>Participation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMER__PARTICIPATION = 2;

  /**
   * The number of structural features of the '<em>Customer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.iSCL.impl.CompanyImpl <em>Company</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.iSCL.impl.CompanyImpl
   * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getCompany()
   * @generated
   */
  int COMPANY = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__NAME = 0;

  /**
   * The number of structural features of the '<em>Company</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.iSCL.impl.InsurableObjectImpl <em>Insurable Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.iSCL.impl.InsurableObjectImpl
   * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getInsurableObject()
   * @generated
   */
  int INSURABLE_OBJECT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSURABLE_OBJECT__NAME = 0;

  /**
   * The feature id for the '<em><b>Owner</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSURABLE_OBJECT__OWNER = 1;

  /**
   * The number of structural features of the '<em>Insurable Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSURABLE_OBJECT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.iSCL.ContractType <em>Contract Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.iSCL.ContractType
   * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getContractType()
   * @generated
   */
  int CONTRACT_TYPE = 10;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.iSCL.Coverage <em>Coverage</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.iSCL.Coverage
   * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getCoverage()
   * @generated
   */
  int COVERAGE = 11;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.iSCL.Contract <em>Contract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contract</em>'.
   * @see uk.ac.kcl.inf.iSCL.Contract
   * @generated
   */
  EClass getContract();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.Contract#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see uk.ac.kcl.inf.iSCL.Contract#getType()
   * @see #getContract()
   * @generated
   */
  EAttribute getContract_Type();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.Contract#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.iSCL.Contract#getName()
   * @see #getContract()
   * @generated
   */
  EAttribute getContract_Name();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.iSCL.Contract#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Company</em>'.
   * @see uk.ac.kcl.inf.iSCL.Contract#getCompany()
   * @see #getContract()
   * @generated
   */
  EReference getContract_Company();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.iSCL.Contract#getCustomers <em>Customers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Customers</em>'.
   * @see uk.ac.kcl.inf.iSCL.Contract#getCustomers()
   * @see #getContract()
   * @generated
   */
  EReference getContract_Customers();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.iSCL.Contract#getInsurableObjects <em>Insurable Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Insurable Objects</em>'.
   * @see uk.ac.kcl.inf.iSCL.Contract#getInsurableObjects()
   * @see #getContract()
   * @generated
   */
  EReference getContract_InsurableObjects();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.iSCL.Contract#getPaymentTerm <em>Payment Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Payment Term</em>'.
   * @see uk.ac.kcl.inf.iSCL.Contract#getPaymentTerm()
   * @see #getContract()
   * @generated
   */
  EReference getContract_PaymentTerm();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.iSCL.Contract#getClaimTerm <em>Claim Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Claim Term</em>'.
   * @see uk.ac.kcl.inf.iSCL.Contract#getClaimTerm()
   * @see #getContract()
   * @generated
   */
  EReference getContract_ClaimTerm();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.iSCL.Contract#getViolationTerms <em>Violation Terms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Violation Terms</em>'.
   * @see uk.ac.kcl.inf.iSCL.Contract#getViolationTerms()
   * @see #getContract()
   * @generated
   */
  EReference getContract_ViolationTerms();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.iSCL.PaymentTerm <em>Payment Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Payment Term</em>'.
   * @see uk.ac.kcl.inf.iSCL.PaymentTerm
   * @generated
   */
  EClass getPaymentTerm();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.PaymentTerm#getPremium <em>Premium</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Premium</em>'.
   * @see uk.ac.kcl.inf.iSCL.PaymentTerm#getPremium()
   * @see #getPaymentTerm()
   * @generated
   */
  EAttribute getPaymentTerm_Premium();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.PaymentTerm#getPeriod <em>Period</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Period</em>'.
   * @see uk.ac.kcl.inf.iSCL.PaymentTerm#getPeriod()
   * @see #getPaymentTerm()
   * @generated
   */
  EAttribute getPaymentTerm_Period();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.PaymentTerm#getIncrease <em>Increase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Increase</em>'.
   * @see uk.ac.kcl.inf.iSCL.PaymentTerm#getIncrease()
   * @see #getPaymentTerm()
   * @generated
   */
  EAttribute getPaymentTerm_Increase();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.iSCL.ClaimTerm <em>Claim Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Claim Term</em>'.
   * @see uk.ac.kcl.inf.iSCL.ClaimTerm
   * @generated
   */
  EClass getClaimTerm();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.ClaimTerm#getClaim <em>Claim</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Claim</em>'.
   * @see uk.ac.kcl.inf.iSCL.ClaimTerm#getClaim()
   * @see #getClaimTerm()
   * @generated
   */
  EAttribute getClaimTerm_Claim();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.iSCL.ClaimTerm#getClaimer <em>Claimer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Claimer</em>'.
   * @see uk.ac.kcl.inf.iSCL.ClaimTerm#getClaimer()
   * @see #getClaimTerm()
   * @generated
   */
  EReference getClaimTerm_Claimer();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.iSCL.ViolationTerm <em>Violation Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Violation Term</em>'.
   * @see uk.ac.kcl.inf.iSCL.ViolationTerm
   * @generated
   */
  EClass getViolationTerm();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.iSCL.ContractCancellationTerm <em>Contract Cancellation Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contract Cancellation Term</em>'.
   * @see uk.ac.kcl.inf.iSCL.ContractCancellationTerm
   * @generated
   */
  EClass getContractCancellationTerm();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.ContractCancellationTerm#isCancelled <em>Cancelled</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cancelled</em>'.
   * @see uk.ac.kcl.inf.iSCL.ContractCancellationTerm#isCancelled()
   * @see #getContractCancellationTerm()
   * @generated
   */
  EAttribute getContractCancellationTerm_Cancelled();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.iSCL.ClaimReductionTerm <em>Claim Reduction Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Claim Reduction Term</em>'.
   * @see uk.ac.kcl.inf.iSCL.ClaimReductionTerm
   * @generated
   */
  EClass getClaimReductionTerm();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.ClaimReductionTerm#getClaimReduction <em>Claim Reduction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Claim Reduction</em>'.
   * @see uk.ac.kcl.inf.iSCL.ClaimReductionTerm#getClaimReduction()
   * @see #getClaimReductionTerm()
   * @generated
   */
  EAttribute getClaimReductionTerm_ClaimReduction();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.iSCL.PremiumIncreaseTerm <em>Premium Increase Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Premium Increase Term</em>'.
   * @see uk.ac.kcl.inf.iSCL.PremiumIncreaseTerm
   * @generated
   */
  EClass getPremiumIncreaseTerm();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.PremiumIncreaseTerm#getPremiumIncrease <em>Premium Increase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Premium Increase</em>'.
   * @see uk.ac.kcl.inf.iSCL.PremiumIncreaseTerm#getPremiumIncrease()
   * @see #getPremiumIncreaseTerm()
   * @generated
   */
  EAttribute getPremiumIncreaseTerm_PremiumIncrease();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.iSCL.Customer <em>Customer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Customer</em>'.
   * @see uk.ac.kcl.inf.iSCL.Customer
   * @generated
   */
  EClass getCustomer();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.Customer#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.iSCL.Customer#getName()
   * @see #getCustomer()
   * @generated
   */
  EAttribute getCustomer_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.Customer#getCoverage <em>Coverage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Coverage</em>'.
   * @see uk.ac.kcl.inf.iSCL.Customer#getCoverage()
   * @see #getCustomer()
   * @generated
   */
  EAttribute getCustomer_Coverage();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.Customer#getParticipation <em>Participation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Participation</em>'.
   * @see uk.ac.kcl.inf.iSCL.Customer#getParticipation()
   * @see #getCustomer()
   * @generated
   */
  EAttribute getCustomer_Participation();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.iSCL.Company <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Company</em>'.
   * @see uk.ac.kcl.inf.iSCL.Company
   * @generated
   */
  EClass getCompany();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.Company#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.iSCL.Company#getName()
   * @see #getCompany()
   * @generated
   */
  EAttribute getCompany_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.iSCL.InsurableObject <em>Insurable Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insurable Object</em>'.
   * @see uk.ac.kcl.inf.iSCL.InsurableObject
   * @generated
   */
  EClass getInsurableObject();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.iSCL.InsurableObject#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.iSCL.InsurableObject#getName()
   * @see #getInsurableObject()
   * @generated
   */
  EAttribute getInsurableObject_Name();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.iSCL.InsurableObject#getOwner <em>Owner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Owner</em>'.
   * @see uk.ac.kcl.inf.iSCL.InsurableObject#getOwner()
   * @see #getInsurableObject()
   * @generated
   */
  EReference getInsurableObject_Owner();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.iSCL.ContractType <em>Contract Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Contract Type</em>'.
   * @see uk.ac.kcl.inf.iSCL.ContractType
   * @generated
   */
  EEnum getContractType();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.iSCL.Coverage <em>Coverage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Coverage</em>'.
   * @see uk.ac.kcl.inf.iSCL.Coverage
   * @generated
   */
  EEnum getCoverage();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ISCLFactory getISCLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.iSCL.impl.ContractImpl <em>Contract</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.iSCL.impl.ContractImpl
     * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getContract()
     * @generated
     */
    EClass CONTRACT = eINSTANCE.getContract();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT__TYPE = eINSTANCE.getContract_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT__NAME = eINSTANCE.getContract_Name();

    /**
     * The meta object literal for the '<em><b>Company</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__COMPANY = eINSTANCE.getContract_Company();

    /**
     * The meta object literal for the '<em><b>Customers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__CUSTOMERS = eINSTANCE.getContract_Customers();

    /**
     * The meta object literal for the '<em><b>Insurable Objects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__INSURABLE_OBJECTS = eINSTANCE.getContract_InsurableObjects();

    /**
     * The meta object literal for the '<em><b>Payment Term</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__PAYMENT_TERM = eINSTANCE.getContract_PaymentTerm();

    /**
     * The meta object literal for the '<em><b>Claim Term</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__CLAIM_TERM = eINSTANCE.getContract_ClaimTerm();

    /**
     * The meta object literal for the '<em><b>Violation Terms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__VIOLATION_TERMS = eINSTANCE.getContract_ViolationTerms();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.iSCL.impl.PaymentTermImpl <em>Payment Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.iSCL.impl.PaymentTermImpl
     * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getPaymentTerm()
     * @generated
     */
    EClass PAYMENT_TERM = eINSTANCE.getPaymentTerm();

    /**
     * The meta object literal for the '<em><b>Premium</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYMENT_TERM__PREMIUM = eINSTANCE.getPaymentTerm_Premium();

    /**
     * The meta object literal for the '<em><b>Period</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYMENT_TERM__PERIOD = eINSTANCE.getPaymentTerm_Period();

    /**
     * The meta object literal for the '<em><b>Increase</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYMENT_TERM__INCREASE = eINSTANCE.getPaymentTerm_Increase();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.iSCL.impl.ClaimTermImpl <em>Claim Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.iSCL.impl.ClaimTermImpl
     * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getClaimTerm()
     * @generated
     */
    EClass CLAIM_TERM = eINSTANCE.getClaimTerm();

    /**
     * The meta object literal for the '<em><b>Claim</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLAIM_TERM__CLAIM = eINSTANCE.getClaimTerm_Claim();

    /**
     * The meta object literal for the '<em><b>Claimer</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLAIM_TERM__CLAIMER = eINSTANCE.getClaimTerm_Claimer();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.iSCL.impl.ViolationTermImpl <em>Violation Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.iSCL.impl.ViolationTermImpl
     * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getViolationTerm()
     * @generated
     */
    EClass VIOLATION_TERM = eINSTANCE.getViolationTerm();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.iSCL.impl.ContractCancellationTermImpl <em>Contract Cancellation Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.iSCL.impl.ContractCancellationTermImpl
     * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getContractCancellationTerm()
     * @generated
     */
    EClass CONTRACT_CANCELLATION_TERM = eINSTANCE.getContractCancellationTerm();

    /**
     * The meta object literal for the '<em><b>Cancelled</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT_CANCELLATION_TERM__CANCELLED = eINSTANCE.getContractCancellationTerm_Cancelled();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.iSCL.impl.ClaimReductionTermImpl <em>Claim Reduction Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.iSCL.impl.ClaimReductionTermImpl
     * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getClaimReductionTerm()
     * @generated
     */
    EClass CLAIM_REDUCTION_TERM = eINSTANCE.getClaimReductionTerm();

    /**
     * The meta object literal for the '<em><b>Claim Reduction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLAIM_REDUCTION_TERM__CLAIM_REDUCTION = eINSTANCE.getClaimReductionTerm_ClaimReduction();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.iSCL.impl.PremiumIncreaseTermImpl <em>Premium Increase Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.iSCL.impl.PremiumIncreaseTermImpl
     * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getPremiumIncreaseTerm()
     * @generated
     */
    EClass PREMIUM_INCREASE_TERM = eINSTANCE.getPremiumIncreaseTerm();

    /**
     * The meta object literal for the '<em><b>Premium Increase</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREMIUM_INCREASE_TERM__PREMIUM_INCREASE = eINSTANCE.getPremiumIncreaseTerm_PremiumIncrease();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.iSCL.impl.CustomerImpl <em>Customer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.iSCL.impl.CustomerImpl
     * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getCustomer()
     * @generated
     */
    EClass CUSTOMER = eINSTANCE.getCustomer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUSTOMER__NAME = eINSTANCE.getCustomer_Name();

    /**
     * The meta object literal for the '<em><b>Coverage</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUSTOMER__COVERAGE = eINSTANCE.getCustomer_Coverage();

    /**
     * The meta object literal for the '<em><b>Participation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUSTOMER__PARTICIPATION = eINSTANCE.getCustomer_Participation();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.iSCL.impl.CompanyImpl <em>Company</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.iSCL.impl.CompanyImpl
     * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getCompany()
     * @generated
     */
    EClass COMPANY = eINSTANCE.getCompany();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPANY__NAME = eINSTANCE.getCompany_Name();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.iSCL.impl.InsurableObjectImpl <em>Insurable Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.iSCL.impl.InsurableObjectImpl
     * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getInsurableObject()
     * @generated
     */
    EClass INSURABLE_OBJECT = eINSTANCE.getInsurableObject();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSURABLE_OBJECT__NAME = eINSTANCE.getInsurableObject_Name();

    /**
     * The meta object literal for the '<em><b>Owner</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSURABLE_OBJECT__OWNER = eINSTANCE.getInsurableObject_Owner();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.iSCL.ContractType <em>Contract Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.iSCL.ContractType
     * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getContractType()
     * @generated
     */
    EEnum CONTRACT_TYPE = eINSTANCE.getContractType();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.iSCL.Coverage <em>Coverage</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.iSCL.Coverage
     * @see uk.ac.kcl.inf.iSCL.impl.ISCLPackageImpl#getCoverage()
     * @generated
     */
    EEnum COVERAGE = eINSTANCE.getCoverage();

  }

} //ISCLPackage
