/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Premium Increase Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.iSCL.PremiumIncreaseTerm#getPremiumIncrease <em>Premium Increase</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getPremiumIncreaseTerm()
 * @model
 * @generated
 */
public interface PremiumIncreaseTerm extends ViolationTerm
{
  /**
   * Returns the value of the '<em><b>Premium Increase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Premium Increase</em>' attribute.
   * @see #setPremiumIncrease(int)
   * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getPremiumIncreaseTerm_PremiumIncrease()
   * @model
   * @generated
   */
  int getPremiumIncrease();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.iSCL.PremiumIncreaseTerm#getPremiumIncrease <em>Premium Increase</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Premium Increase</em>' attribute.
   * @see #getPremiumIncrease()
   * @generated
   */
  void setPremiumIncrease(int value);

} // PremiumIncreaseTerm
