/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.iSCL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Violation Term</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.iSCL.ISCLPackage#getViolationTerm()
 * @model
 * @generated
 */
public interface ViolationTerm extends EObject
{
} // ViolationTerm
