/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.iscl.ui.internal.IsclActivator;

public class ISCLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IsclActivator.getInstance().getInjector("uk.ac.kcl.inf.ISCL");
	}

}
